modLoader="javafml"
loaderVersion="[4,)"
license="MIT"  

[[mods]]
modId="spanishdelight"
version="1.0.0"
displayName="Spanish Delight"
authors="DevJulen, fragi0"
description='''
Spanish Delight expands upon Farmer's Delight cooking system, introducing traditional Spanish cuisine dishes like Spanish Tortilla, Paella, Gazpacho and more.

Original Mod by DevJulen.
NeoForge 1.21 Port & Rebuild by fragi0.
'''
logoFile="spanishdelightbanner.png"
logoBlur=true
displayURL="https://github.com/fragi0/SpanishDelight---NeoForge1.21.1"

# Dependencias
[[dependencies.spanishdelight]]
modId="neoforge"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.spanishdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.spanishdelight]]
modId="farmersdelight"
mandatory=true
# Ajustado a versi√≥n compatible con 1.21
versionRange="[1.2.4,)"
ordering="AFTER"
side="BOTH"
