modLoader="neoforge"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
logoFile="spanishdelightbanner.png"
logoBlur=true
displayURL="https://github.com/fragi0/SpanishDelight---NeoForge1.21.1"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.2.4,)"
    ordering="NONE"
    side="BOTH"
